### ISSUE TITLE
Re-ingest the Stage 2 CFHTLS data to site

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#248]
All these subjects live in the same dataset, and none are retired. Should be an easy re-ingest!

**Comment by drphilmarshall** [comment]
@stuartlynn  - we're just talking about site development work prior to the next project, and realized that you will also need a bunch of images up on the site in order to test SWAPr more fully. Can we get the beta site repopulated with CFHTLS stage 2 please? Thanks!

**Comment by anupreeta27** [comment]
@parrish @stuartlynn 
Could you please repopulate the beta site with CFHTLS stage 2 subjects? I will be giving a talk mid-March at an NSF event which is on "citizen science". It would be really nice if I could show the audience how to do the classifications live!

**Comment by drphilmarshall** [comment]
Agreed: this is long overdue. @stuartlynn, you need this for the SWAPR
testing too :-) Thanks team Adler!

**Comment by stuartlynn** [comment]
Will get on this first thing tomorrow. Thanks for the reminder


—

**Comment by stuartlynn** [comment]
Just so I am sure I am getting this right is it the subjects with metadata.data_set = D7 that you want reactivated?

**Comment by drphilmarshall** [comment]
D7 sounds like a CFHTLS stage 1 dataset, correct? This would be just fine,
thanks.

@chrissnyder, can you please checkout the CFHTLS_Stage1 branch and push
this to the beta app? That way the spotters guide etc will match the
re-ingested data.

**Comment by chrissnyder** [comment]
To be clear, this branch, right? https://github.com/drphilmarshall/Lens-Zoo/tree/CFHTLS_stage2

**Comment by drphilmarshall** [comment]
No, the stage 1 branch:
https://github.com/drphilmarshall/Lens-Zoo/tree/CFHTLS_stage1

IF D7 is a stage 1 dataset, let's put up the stage 1 web app. The two goals
for this beta site are 1) enable Stuart to test SWAPR against SWAP, and 2)
enable live demos of the site during talks etc. We can be developing the
app for the DES data in a separate branch that is not live, for now.

**Comment by chrissnyder** [comment]
Oops, I totally misread that.

Stage 1 branch online at http://spacewarps.org/swapr/

**Comment by stuartlynn** [comment]
Data is reactivating now. All synthetics and actual images that have DR7 as their metadata. Let me know if there are any issues or anything looks wrong. Closing this issue now!

**Comment by drphilmarshall** [comment]
Looks good to me - thanks both! :-)

**Comment by anupreeta27** [comment]
sorry, i can't see any change on the spacewarps or its beta version of the
website. could you please point me to the right link to see the changes?
thanks!

**Comment by aprajita** [comment]
http://spacewarps.org/swapr/

**Comment by anupreeta27** [comment]
thanks, aprajita!
@stuartlynn @parrish @chrissnyder 
thanks, i can see images in the classification interface. the tutorial text is not enabled and there's no feedback on the sim images although i see feedback on the dud images. could you please fix this?

**Comment by drphilmarshall** [comment]
​I can reproduce this error: in my first look I must have only gotten duds.

**Comment by stuartlynn** [comment]
So I think that there must be a bug in that branch. Getting a javascript error every time the app pulls a simulation. Going to try and figure out whats wrong with it, it might have been a problem that was fixed in another branch but never pulled back in to this one

**Comment by stuartlynn** [comment]
Yeah ok wow I think that stage one branch is really far behind the currently running version of the code. Phill is there anyway we can use the Vics branch with some of the configuration settings modified to run with this dataset? That way all the bug reports and enhancements to the site will remain intact.

**Comment by aprajita** [comment]
@drphilmarshall is there any harm just making stage 2 cfhtls the available under the swapr URL

**Comment by stuartlynn** [comment]
Can you let me know what the identifier for that is? If D7 was for stage 1 CFHTLS is D8 for stage 2?

**Comment by aprajita** [comment]
Hi stuart
afraid not, it didnt work that way
D1-D11 are all stage 1 and we just resurrected subjects for stage 2, but before we do anythng. perhaps phil, anu and I should have a think about what's the best to do wrt to data and interface
thanks
aprajita.

**Comment by anupreeta27** [comment]
@stuartlynn 
as aprajita said, we didn't have a different identifier for stage 2 subjects but perhaps, if you could enable the stage 2 version of the website and simply ingest any of the datasets, it might work without any of those issues. please correct me @drphilmarshall, if i am wrong.

**Comment by drphilmarshall** [comment]
I think that should work: it's certainly worth a go. Let's try the
CFHTLS_stage2 app, same D7 dataset.

I'm not sure how important the out of dateness of CFHTLS_stage1 is, as
we'll probably want to branch the DES site from the VICS82 site, but still.

**Comment by anupreeta27** [comment]
@stuartlynn did you manage to enable the stage2 app and D7 dataset?

**Comment by stuartlynn** [comment]
Should be active now : http://spacewarps.org/swapr

**Comment by drphilmarshall** [comment]
Thanks Stuart! Site looks OK, but I still have problems with the training
images:

* If there's a sim there and I don't mark it, I get the "actually there is
a lens" feedback message
* If there's a sim there and I mark it, I get neither a congratulation
message nor a "actually" message
* If the subject is a dud, and I don't mark it, I get a congratulations
feedback message
* If the subject is a dud, and I mark it, I get a feedback message but the
text is not displayed, only the name of the tex variable (eg
`feedback.dcreateSimulationMissedFeedbackud_missed_details` or something)

So there's at least two problems with the web app code:

The message formatting is probably just some sort of typo in the script.

The sim marker not leading to a sim congratulation message is weirder: but
maybe you can check the SWAPR outputs to debug this!

**Comment by stuartlynn** [comment]
That very strange. Ok will look in to it some more.




Cheers




Stuart


—

**Comment by anupreeta27** [comment]
@stuartlynn thanks for checking. the quick dashboard doesn't work either (it didn't work earlier too).

**Comment by stuartlynn** [comment]
The dud message should be fixed now. Working on the sim found feedback

**Comment by stuartlynn** [comment]
Ok so the issue with both the quick dashboard and the sim found feedback is a cross domain image one. The Images are hosted on the zooniverse-static bucket and get redirected from the spacewarps.org url. This is the new way we are doing hosting but it means that the browser doesn't trust those images and so doesn't allow access to the mask data and the data needed for the dashboard. Trying to find a work around now.

**Comment by stuartlynn** [comment]
Ok all those issues should be fixed and deployed now. The new version of the code is up at this branch : https://github.com/zooniverse/Lens-Zoo/tree/swapr 

Going to close the issue now. Going to start looking in to if the classification ordering makes a difference again.

**Comment by aprajita** [comment]
thanks Stuart - that looks good!

Sorry I know this isn't the right place but do you have any idea who might be able to helpus with the dashbaord in talk - it's been broken for sometime and my issue isn't getting any attention...

**Comment by stuartlynn** [comment]
That might be the same issues as the one that was causing it to fail on the main site. Will look in to it.


Cheers




Stuart


—

**Comment by stuartlynn** [comment]
Hey  @aprajita do you have a link to an issue for that problem? Or can describe whats happening to help me track it down?

**Comment by aprajita** [comment]
hi stuart
thanks !

https://github.com/zooniverse/Lens-Zoo/issues/257

**Comment by anupreeta27** [comment]
@stuartlynn thanks for getting this working again. most of the features seem to be working. i notice one strange thing that some times there are images appearing from the second survey VICS82 in between the data from the first survey CFHTLS. could you please check this?
