### ISSUE TITLE
SW Dashboard not working

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Lens-Zoo#257]
Hi there
For the last few months I cant seem to get the SW dashboard to work, both in displaying images when i follow the "open in tools" link in talk and for downloading the FITS files. I am not sure if this is the same thing as #238 but could someone please take a look? Perhaps @parrish @chrissnyder ?
e.g. http://tools.zooniverse.org/#/dashboards/spacewarp/5464980627b5620a8f000006

Many thanks!
Aprajita.
![image](https://cloud.githubusercontent.com/assets/1917970/5028679/582fcca6-6b36-11e4-904f-383530f4cbe5.png)

**Comment by aprajita** [comment]
@parrish @chrissnyder: Happy New Year! Would anyone have time to look at this?

**Comment by aprajita** [comment]
Hi @parrish @chrissnyder
Does anyone in the team have time to look at this please?
Many thanks
Aprajita.

**Comment by aprajita** [comment]
@stuartlynn thanks for looking into this!

**Comment by stuartlynn** [comment]
@aprajita Should be resolved now. Thanks @edpaget for the help

**Comment by aprajita** [comment]
Wonderful stuff @stuartlynn & @edpadget - thank you very much!! & just in time for any renewed SW interest from stargazing live. Thanks again.
