### ISSUE TITLE
URGENT: Make web page of SW-VICS82 Volunteers

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Lens-Zoo#259]
It is likely that the 9io9 result will be publicised on Stargazing Live this week (not sure when) please could someone create a list of the zooniverse IDs of all the volunteers participating in the VICS82 classification last year. I realise this will be a very long list but everyone's classifications counted (not jsut those that saw this particular subject).

@stuartlynn @edpaget @parrish @chrissnyder anyone help?

it can be at a temporray URL at the moment or on the SW site. Thanks!!

**Comment by stuartlynn** [comment]
Hi @aprajita  I can do this. Whats the best way to identify those people? People who classified in a given time range, on a given set of subjects(and if so how do I identify them from the subject metadata)?

If you can let me know I can produce the list and the website.

**Comment by drphilmarshall** [comment]
Thanks Stuart, Aprajita.

Re: where this should go: @chrissnyder built a nice "results" area (linked
from the side navigation bar) that could host this:

http://spacewarps.org/#/projects

I can't see what tabs each project has at the moment (the link is dead),
but one of them could be "Participants" and host the list we are asking
for. We have some work to do adding content in the other tabs, introducing
the project and summarizing the new candidates - but this is somewhat less
urgent than having a URL of the participant list to put in the first paper.
Thanks!

I think this list should be anyone who classified a VICS82 test subject; I
believe the subjects have a metadata item called "survey" (or perhaps
"project") and the value we are looking for is "VICS82". Subjects that
don't have this item at all are from CFHTLS. We should ignore the initial
tutorial image when collecting usernames though (lots of people see that
and don't get past it - and hence didn't contribute to the project.)

**Comment by aprajita** [comment]
Hi @stuartlynn that would be great!! Although @chrislintott mentioned he was also putting a list together but am not sure if he has been able to yet. I think think there's a SW2 label in the metadata/database or we could just pick activity between the 7th-10th Jan. @drphilmarshall can you please confirm.

**Comment by stuartlynn** [comment]
I think the results page will be a good place to host this. Will check with @chrissnyder and prepare that list to go on there. Just a heads up as well we are changing the home page tonight to have a large link to the current stargazing live project and the other two previous ones.

**Comment by aprajita** [comment]
ahh i just see @drphilmarshall posted just before me. 

i think a SW-VICS82 participants page under results would be fine. 

We will also need a SW-CFHTLS list in the next couple of weeks for those papers.

Is there any reason not to just have a single cumulative list of SW users that we add to?

**Comment by drphilmarshall** [comment]
Yes - classification date in that range is a good cross-check and/or
back-up plan, if I'm wrong about the "survey" metadata field.

@stuartlynn, the current SW homepage is the mosaic of 5 new VICS82
candidates, with the volunteers who classified them. If you need to move
this content, you could put it in a "New Lens Candidates" tab in the
 projects/VICS82 area, parallel to the "Participants" one.

I think it's better to have one particpant list per project, so that the
papers for that project can point to the actual volunteers who did that
work. Aprajita's right, we'll need a CFHTLS one soon! :-)

**Comment by stuartlynn** [comment]
@drphilmarshall That content will still be there we are just adding the links as well. Just pushed the new homepage to beta so you can see what it looks like: http://spacewarps.org/beta/

**Comment by drphilmarshall** [comment]
Got it! Looks good. You might want to add a line of text, same font as
"Last year you.." just above the VICS82 results, saying:

"Here are the new gravitational lens candidates you found during BBC
Stargazing Live 2014:"

just to make it clear that those objects are not new supernovae! :-)

**Comment by stuartlynn** [comment]
Sounds good

**Comment by stuartlynn** [comment]
Hey so we have three tabs for the results page for each project. Summary, Discoveries and Contributors. @drphilmarshall can you write me a quick summary and let me know if the discoveries should be different from what is on the home page?

**Comment by aprajita** [comment]
Hi @stuartlynn we don't have a final list of discoveries from VICS82 yet, so perhaps just say
 Under Summary:
Space Warps VICS82 was launched on BBC Stargazing Live! in January 2014. A whopping 7,500,000 classifications were made by more than 50,000 volunteers in just three days. Visitors to Space Warps were presented with thousands of images and found tens of potential gravitational lenses. Some of the promising candidates are shown on XX. One of them is a spectacular red ring dubbed 9io9. See what people are saying about it http://talk.spacewarps.org/#/subjects/ASW0009io9 where we got some fantastic data that are about to be submitted to a scientific journal for publication. Thanks to all who've participated!! Check back here in a few months for more info on the full VICS82 sample.

**Comment by drphilmarshall** [comment]
Perfect. For now the "discoveries" can be just the homepage content, as you
say. To make it clear what we mean by "Discoveries" I'd suggest we include
a single line of text on this tab, above the images, that says" "Here are
some of the new gravitational lens candidates that were identified by the
Space Warps volunteers, ready for further study by the science and survey
teams:"  Thanks @stuartlynn! :-)

**Comment by stuartlynn** [comment]
Ok this is up here now. Its not quite using the page that @chrissnyder set up because its weird to just have on survey in there but we can transition to that easily when we need to. 

http://spacewarps.org/#/projects

**Comment by aprajita** [comment]
Hi @stuartlynn Please could you change  XX in the text to a hyperlink where the first candidates are shown _ i guess that's on the home page (as I think there's no actual results tab). Also the 9io9 link http://talk.spacewarps.org/#/subjects/ASW0009io9 should be hyperlinked.
thanks for putting this together so quickly!

**Comment by stuartlynn** [comment]
Will do. Sorry I didn't spot the placeholder!

**Comment by aprajita** [comment]
thanks @stuartlynn -  sorry to see that you are still up & working!
BTW we'll need to sort out the results page in time for the CFHT papers in a few weeks time, after the SGLive rush is over...

**Comment by stuartlynn** [comment]
This should be resolved now. Closing the issue
