### ISSUE TITLE
switch back to the original SW main page

### ISSUE THREAD

**Issue by anupreeta27** [zooniverse/Lens-Zoo#260]
@chrissnyder @parrish @stuartlynn 
Could we please remove the stargazing live announcement for supernovae and bring back the original SW main page? We are planning to submit our SW papers soon and put out some blog posts, so we expect more traffic to SW website.

**Comment by stuartlynn** [comment]
Hi @anupreeta27. Do you mean the old page with the results or the very original SW page?

**Comment by anupreeta27** [comment]
anything is fine. we can go with the old page with results, if that's easier.
thanks!

**Comment by stuartlynn** [comment]
Should be back to pre space warps

**Comment by anupreeta27** [comment]
many thanks!
