### ISSUE TITLE
CFHTLS and VICS82 project participants lists

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#261]
We are submitting two papers about the CFHTLS project to the arxiv on Weds (April 22) and would like to include the URL of the page showing all the CFHTLS project contributors usernames, please! You made this for VICS82 a few weeks ago ( #259 ), now we need the CFHTLS ones as well please. I think you can get the list from all classifications with survey=CFHTLS (or perhaps project=CFHTLS), or no survey keyword - I think you have done this search before...

The current site shows a version rolled back to some intermediate commit where the "Results" sidebar button takes you to http://spacewarps.org/#/results/ , which is where @chrissnyder started developing the tabbed pages we need. In issue #259 we converged on a tab for each project (CFHTLS first, then VICS82) and then within those tabs, tabs for "Summary", "Discoveries" and "Participants". For now you can put "Coming soon!" in the Summary and Discoveries tabs - its mainly the Participants we need. The "Results" button should take the user through to this area, which is really a projects area. I'd like us to be able to provide links to the URL http://spacewarps.org/#/projects/CFHTLS from our papers: "projects" is better than "results", so that we can show that SW has served more than one survey team ("results" sounds a little final).

We'll also need to put up images of the CFHTLS candidates, and a summary of the project, but these can be separate issues. Which branch should we be working in? Is it time to merge back to master?

**Comment by drphilmarshall** [comment]
See also previous discussion at https://github.com/drphilmarshall/SpaceWarps/issues/81- the above is just re-iteration, plus query about branch management. Thanks! :-)

**Comment by chrissnyder** [comment]
I can find classifications for VICS82, but not for CFHTLS. Would the correct assumption be that any classification done without a project annotation be for CFHTLS?

Also I don't know if I'm going to be able to put all the names on the page itself, as just the VICS82 usernames ended up at ~35mb. Would a direct link to a text file be sufficient?

**Comment by chrissnyder** [comment]
Also I'm working off the results-page branch, as crazy as that is. As soon as this round of updates is done, I'll push it to master plus clean up some of the various branches. Pretty sure there are only a couple in there that are still relevant.

**Comment by drphilmarshall** [comment]
OK, thanks Chris.

The plain text presentation of 60,000 usernames should not even come close
to 35Mb, so there is something funny going on I think! @stuartlynn, can you
help us out please? Wasn't it you that made us the list of usernames for
VICS82? I would think it shoudl be no problem displaying another 37000
usernames for CFHTLS on a static webpage.

Thanks again!

**Comment by chrissnyder** [comment]
Still not finding which classifications belong to CFHTLS. Do you have an example classification so I can see what to search on?

**Comment by drphilmarshall** [comment]
Hi Chris: here's how we test for project name in the classification table:

        project = "CFHTLS"
        for annotation in annotations:
            if annotation.has_key('project'):
                project = annotation['project']

We only implemented the project annotation for VICS82, so all previous
classifications were unmarked in this way, and so should be interpreted as
CFHTLS. You should find around 37000 unique usernames (ie including IP
addresses. Interested to know how many registered users we had!

Thanks!

**Comment by chrissnyder** [comment]
Ah OK that makes sense. I've pushed the VICS82 contributors to the results page. Will have the CFHTLS ones online in a bit.

**Comment by drphilmarshall** [comment]
I saw that too! Lead developer for SW VICS82, rock on.

Our papers are now submitted to the arxiv, @chrissnyder: that means we will be getting a lot of traffic today (Wednesday!). Can you please prioritize getting the CFHTLS usernames up into the CFHTLS/contributors page? I submitted a pull request that you might want to merge first. Thanks!

**Comment by stuartlynn** [comment]
Generated those lists for chris and send them through so should be able to get the results page up soon.

**Comment by drphilmarshall** [comment]
Thanks very much! [The page](http://spacewarps.org/#/projects/CFHTLS/contributors) looks great.
