### ISSUE TITLE
Provide summary of CFHTLS project

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#263]
Just paste in titles and abstract of papers?

**Comment by drphilmarshall** [comment]
@anupreeta27 I *think* we should provide links to the most up to date PDF, in the repo, but it might also be nice to provide the arxiv links - can you let us know once you have them, please? Thanks!

**Comment by anupreeta27** [comment]
here they are:
http://arxiv.org/abs/1504.06148
http://arxiv.org/abs/1504.05587

**Comment by drphilmarshall** [comment]
Thanks Anu!
