### ISSUE TITLE
Candidate lists on Discoveries pages

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#265]
Rough suggested plan:

* [x] Copy in the "here's what you found" content from [home.eco](https://github.com/zooniverse/Lens-Zoo/blob/results-page/app/views/home.eco)
* [x] Make it translateable
* [x] Hack a `candidate-list` class into the [discoveries.eco](https://github.com/zooniverse/Lens-Zoo/blob/results-page/app/views/results/CFHTLS/discoveries.eco) page, like the one currently in use in [home.eco](https://github.com/zooniverse/Lens-Zoo/blob/results-page/app/views/home.eco)
* [x] Fill code with G > 2 CFHTLS candidates from paper 2 (just need ASW IDs)
* [x] Remove observer IDs
* [x] Make each image a hyperlink to the corresponding subject page in `Talk`
* [ ] Submit pull request

**Comment by anupreeta27** [comment]
@drphilmarshall  - is this the page where we plan to put ALL (new+known) candidates with G >0 not just G>2. If yes, I already have made small cutouts centered on the candidates (.pngs). I just need to know, if I should make the tar available somewhere and to who -or- should I convert it into a gallery like in paper 2 (an array of annotated pngs split over several pdf pages). 
In any case, pngs should be annotated with similar info as we have in the paper.

**Comment by drphilmarshall** [comment]
To answer this properly we need to decide who our target audience is, and
relatedly what we want to host on the team website (currently at
http://drphilmarshall.github.io/SpaceWarps/). My feeling is that the app
should mainly function as advertising, and mainly to the volunteer
community - in this model it would show images of new candidates, hopefully
linked to Talk, present brief summaries of projects and links to papers,
and then provide links that people can follow to find out more - and the
place where we would put this extra material would be the team website
(where we can change things around faster, and the editing is simpler!).

Whatever we decide, I agree that having annotated small cutouts on the app
results page would be good - mainly because these particular images will
get copied and passed around the internet, so having them display their own
provenance would be good. Some of this can be achieved with a very
informative filename (eg CFHTLSJ020642-095157_SpaceWarps_gri_10x10arcsec.png).
For the annotation itself, I'd go with the object name
(CFHTLSJ020642-095157) at the top, and http://spacewarps.org along the
bottom, and drop the SW ID and grade. We probably want to use smaller font
and gray text, to make the annotation more subtle (so that people want to
use the images!). What do you think?

From a practical point of view, using our own cutouts means either
uploading PNGs to the Lens-Zoo site, or pulling them in from the team
website. I guess if we made a compete gallery on our own website, the
easiest thing to do would be the latter (just write links into the app
results page).

**Comment by drphilmarshall** [comment]
Fastest possible route to images on the page = link to paper 2 gallery png.

**Comment by drphilmarshall** [comment]
Hey @chrissnyder thanks for fixing up the formatting! The [hyperlinked VICS82 candidate list](http://spacewarps.org/#/projects/VICS82/discoveries) looks pretty good I think :-) We'll work on getting a CFHTLS gallery up in the same style. Cheers!

**Comment by anupreeta27** [comment]
@drphilmarshall  see this new folder with annotated pngs of all SW candidates 
https://github.com/drphilmarshall/SpaceWarps/tree/master/analysis/projects/CFHTLS/candidates

**Comment by drphilmarshall** [comment]
Thanks @anupreeta27!

Here are some suggestions for formatting in a second iteration - can you
please:

* [ ] Use a san serif font, reduced in size from the current. (For this
application we are trying to be a bit more subtle about the annotation:
they are not figures for a publication, but images for use on the web!)
* [ ] Use the IAU name for the candidate, not the RA/dec coordinates. This
is important, for matching objects with references in the literature.
'01:23:45 06:07:08' would become CFHTLSJ012345+06070. (Note that you need
one more significant figure in the RA than the Dec, so we might want to go
to 012345.6 instead of truncating the dec string. See
http://cds.u-strasbg.fr/vizier/Dic/iau-spec.htx for more details
* [ ] Left-justify the object name in the top left corner
* [ ] Include the string 'spacewarps.org' (all lower case) in the bottom
left hand corner

Thanks!

**Comment by anupreeta27** [comment]
@drphilmarshall 
thinking about this a bit more after your suggestions, i've made some changes - the new annotation looks like this - let me know if you are fine with this.

![cfhtlsj020122-091515_spacewarps_asw00010he_1 3_30asec_gri](https://cloud.githubusercontent.com/assets/1819690/7361495/3dc96fa8-ed94-11e4-888a-7612a0fdef3a.png)

**Comment by anupreeta27** [comment]
ps: i will switch the names to this format - CFHTLS JHHMMSS.s+DDMMS

**Comment by drphilmarshall** [comment]
I like the subtlety (and the font! :-)

Didn't we decide to include the grade on the image? Or do you think it's
enough to propagate it in the filename? (BTW "grade0.3" might be better
than just "0.3" there)

If we leave it off, I'd vote for name on the left, URL on the right (names
should go first, I think). With the longer name, you might have to go back
to top and bottom lefthand corners for the two annotations.

**Comment by anupreeta27** [comment]
i left the grade out since you said these are mostly for use on the web. the filenames will still have the grade, in case people want to use them for sorting the sample.

**Comment by anupreeta27** [comment]
@drphilmarshall  this list says http://cds.u-strasbg.fr/vizier/Dic/formats.htx
that the format - HHMMSS+DDMMSS - this is what i had earlier, why not stick to this?

**Comment by anupreeta27** [comment]
i mean "CFHTLS HHMMSS+DDMMSS" is an acceptable format - why not stick with this?

**Comment by anupreeta27** [comment]
@drphilmarshall  you can find the updated "candidates" dir under analysis/projects/CFHTLS

**Comment by drphilmarshall** [comment]
OK, submitting a pull request (to see if @chrissnyder can help with one last bit of eco fixit magic). Thanks for the images, Anu!
