### ISSUE TITLE
Branch strategy

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Lens-Zoo#276]
Pinging @drphilmarshall to the party.

Bit of a meta issue. I don't know if there are plans in the near-term to add an additional dataset to SW, but we should figure out a better strategy for swapping between the various datasets. The branches are out of control as-is.

On a more immediate note, no issues with me merging results-page into master is there? There are also a number of orphaned branches in here that I can cleanup.

**Comment by drphilmarshall** [comment]
Agreed, let's rethink the branches. Tags for projects probably makes more
sense, or maybe even different files in some cases (as you did for the
results pages).

Happy for you to merge into master. Let's be very careful about deleting
branches though, there is valuable work locked up in them!

**Comment by chrissnyder** [comment]
Closed via https://github.com/drphilmarshall/Lens-Zoo/pull/77
