### ISSUE TITLE
CFHTLS Reboot Data Ingestion

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Lens-Zoo#279]
@drphilmarshall Just clarifying a few things here if you have a moment.

I'll be seeing to get the proper SW data live on the site tomorrow. What was the general process in the past whereby which previously used data was reingested? Can I just reactivate the appropriate stage 2 along with the other lists that were sent over? Is there anything else I should be aware of?

**Comment by anupreeta27** [comment]
@chrissnyder do you reactivate stage 2 subjects? i don't think there's anything about stage 2 that we'd like to be reactivated but @drphilmarshall can confirm

**Comment by chrissnyder** [comment]
I haven't touched anything data yet.

**Comment by drphilmarshall** [comment]
Not all of the subjects asked for are stage 2 (in fact very few of them
are!)
We just want to reactivate them and get more classifications of them, which
we can then analyze .It woudl be helpful if the classifications (not the
subjects) were tagged as "reboot" - I think at Stage 2 we tagged
classifications as "stage2" in the coffeescript...

**Comment by chrissnyder** [comment]
Last question. Should I deactivate everything not in the lists provided?

**Comment by aprajita** [comment]
I think so, but @anupreeta27 & @drphilmarshall can confirm

**Comment by anupreeta27** [comment]
that's right. we only want the list of subjects we sent to be active. thanks!

**Comment by chrissnyder** [comment]
@parrish And just so I don't do something stupid, it's OK to just pause all active subjects and just activate the subjects they sent over right? Bit scared to make an irreversible change.

**Comment by parrish** [comment]
Rather than pause them, you'll want to transition them to "complete" since they're actually complete.  I'll drop you an email.

**Comment by aprajita** [comment]
In the case we want to run any tests again in the future (although i don't expect this to be the case) can we still resurrect 'complete' subjects?
thanks
aprajita.

**Comment by parrish** [comment]
Sure

**Comment by chrissnyder** [comment]
Data shuffled, site deployed.

**Comment by drphilmarshall** [comment]
Excellent! Thanks very much, @chrissnyder :-) I'll pull in your site edits so our master branches are in tune.
