### ISSUE TITLE
No sims, only duds in rebooted app?

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#280]
When logged in, I classified a few dozen images and got a handful of duds and no sims. Did the sims ingest properly?

**Comment by chrissnyder** [comment]
Maybe I missed a list? Everything other than the provided lists were deactivated.

**Comment by anupreeta27** [comment]
@chrissnyder i forwarded you the old email which had the sims catalog. please let me know if there's any  problem.

**Comment by chrissnyder** [comment]
Looked over every @anupreeta27 sent, all those should already have been active on the site. Any console errors when finding a sim?

**Comment by drphilmarshall** [comment]
I think this is now fixed - thanks @chrissnyder :-)
