### ISSUE TITLE
No tutorial in rebooted app?

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#281]
When I sign out and refresh the app, I don't see the tutorial. Is that correct behavior (because my IP address is being tracked) or a bug?

Possibly relatedly, I cannot advance beyond the first image I'm shown. JS console error messages are as follows:

    Uncaught TypeError: Cannot read property 'id' of undefined
    Uncaught TypeError: Cannot read property 'zooniverse_id' of undefined

**Comment by chrissnyder** [comment]
Tutorial is purely based on user. Would be a bug then.

Team time is very limited over the next couple weeks, and I don't have an estimated time when we could fix these issues. Any chance you could take a crack?

**Comment by drphilmarshall** [comment]
OK, I traced the missing tutorial bug to this error:

    GET http://spacewarps.org/undefined/projects/spacewarp/talk/users/collection_list 404 (Not Found)

This happens at https://github.com/zooniverse/Lens-Zoo/blob/master/app/controllers/classifier.coffee#L175 when, if the user is not recognised, a bunch of Talk collections are started by the `@setTalkCollections(user, names, descriptions)` command. I think this fails (for some reason) and then the rest of the `onUserChange` function - which includes starting the tutorial - is not executed.

**Comment by drphilmarshall** [comment]
Hopefully the counter reset bug (https://github.com/zooniverse/Lens-Zoo/issues/282) will also be fixed by this.

**Comment by drphilmarshall** [comment]
I think this is now fixed, in the sense that I get the tutorial when I am logged out, as required. There's now issue #290 but that's a separate, well, issue. Thanks @chrissnyder !
