### ISSUE TITLE
CFHTLS QD is requesting IR (iJKs) FITS data

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Lens-Zoo#284]
The quick dashboard on the classification interface does not work yet (in either FF and Chrome) - the page freezes. I guessed this was probably to do with the availability of the FITS images - and yes, its that the app is asking for iJKs images (like VICS82). So, this is a bug left over from the branch merge.

Here's the js console report when I try the QD:

```
GET http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_i.fits.fz 
XMLHttpRequest cannot load http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_i.fits.fz. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://spacewarps.org' is therefore not allowed access. The response had HTTP status code 404.
GET http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_Ks.fits.fz File 
XMLHttpRequest cannot load http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_Ks.fits.fz. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://spacewarps.org' is therefore not allowed access. The response had HTTP status code 404.
GET http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_J.fits.fz  XMLHttpRequest cannot load http://spacewarps.org.s3.amazonaws.com/subjects/raw/CFHTLS_007_1982_J.fits.fz. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://spacewarps.org' is therefore not allowed access. The response had HTTP status code 404.
```

**Comment by drphilmarshall** [comment]
@chrissnyder The fact that the QD is not throwing js errors any more, but that the images are not displaying properly, suggests that it might be that the image settings are off (the "scales" and "nonlinearity parameters"). I checked, and your `quick_dashboard.coffee` code still uses the VICS82 settings. I fixed this in https://github.com/drphilmarshall/Lens-Zoo/commit/a5c390d821f0ad9c479cf595845abe446995117e - I now see that you only merged one commit of mine, not the whole pull request... Hopefully this should solve the problem! Unfortunately I cannot re-open the pull request at https://github.com/zooniverse/Lens-Zoo/pull/287 - but you should be able to pull from me directly.

**Comment by aprajita** [comment]
Hi @chrissnyder, just wondering if you'd seen Phil's response on this issue with QD, perhaps if you can pull from Phil we can see if this fixes the issues. 

We are launching the press announcements Thursday 24th 00:00GMT so if we could fix this before that would be great!

many thanks!
Aprajita

**Comment by chrissnyder** [comment]
Yea I'll have a go at integrating it. I tried the first time around and it
just left the QD blank, which is why I didn't fully merge the PR.

**Comment by drphilmarshall** [comment]
HI @chrissnyder - I see you have got the CFHTLS data into the QD OK (and available for FITS download), but the image doesn't display correctly. It's not the scales though, I see you have those in right - and there's no js error. I am stumped: the only thing I can think of is that the scales are somehow being propagated wrongly. I tried editing the code in the QD branch - I see images now, but the scales are still not right. I don't have time to fix this, though - so I'd say, merge my PR if you like, but probably we shoudl disable the QD while we carry on working on this. Can you do that please? We'll need to comment out the tutorial step that points at the QD too... Thanks!

**Comment by chrissnyder** [comment]
Can do. I'll make an attempt at playin with different scales tonight but if
I can't get it working then I'll just disable it entirely for now.

**Comment by drphilmarshall** [comment]
I think that's sensible, thanks Chris. I'd prefer not to tweak the scales
individually: there must be a more systematic problem at play, to do with
the "calibrations" perhaps. I don't think fits.js has changed any between
CFHTLS stage 1/2 and now, more likely its our own QD library, and most
likely due to VICS82 interference somehow.
