### ISSUE TITLE
Sims not registering accurate markers

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Lens-Zoo#293]
From Els:

Julianne and I are already classifying and we both have had the same thing happening to us. We mark a sim and then we get a message that we've missed it.
See attached screen print.
Julianne has had it happening with over 20 sims.
Is this a known issue ?

Julianne:
The sim issue only seems to be occurring in Chrome (45.0.2454.99 m), I use a Windows 8.1 OS. Seem to be working okay on Firefox (40.0.3) - apart from my classification count always resetting!

Els:
I'm actually at work and here we use Firefox 38.3.0.
I seem to recall I had the same problem when the site went live again with Chrome (not sure which version) I'll let you know tonight.

![simmarkers](https://cloud.githubusercontent.com/assets/1917970/10073256/7a183f0c-62bf-11e5-84b1-357b0f317ba9.jpg)

**Comment by aprajita** [comment]
Moving counter reset problem to another issue

**Comment by aprajita** [comment]
Is this just an alpha channel mask problem in the interface or does it mean that they get a wrong in the database - as this would then affect the agents for these users and therefore the classifications. Do we know if the positions of the clicks are being registered properly in the database - perhaps Chris Davis could take a look at marker locations for some of the images to make sure?

**Comment by drphilmarshall** [comment]
I see this problem too, also using Chrome. It doesn't seem to be completely
universal though - I did get a congratultaory message too, so it could be
that if there is an offset between the alpha image and the marker position,
it's not a very big one.

I think this will *not* affect the agents, since we can register any marker
as a "LENS" vote (as opposed to a "NOT" vote) with the method=False option
in mongodb.digest. But, it's annoying for the volunteers!

@chrissnyder Would you mind please checking the marker position being
recorded against the position of the region of interest in the alpha image?

**Comment by aprajita** [comment]
oops sorry, yes, I forgot that we don't include the x,y position in the lens or not classfication
thanks.

**Comment by aprajita** [comment]
i tried again in Chrome and also only get this message sometimes, and sometimes get the congratulatory message. I'm not sure what's the problem, but agree it's rather confusing for the volunteers. 

@chrissnyder  did you manage to have a look at this?

A couple of examples where I got the missed sim message even though I marked
http://talk.spacewarps.org/?_ga=1.47163431.1484186906.1429653766#/subjects/ASW000286q
http://talk.spacewarps.org/?_ga=1.81625367.1484186906.1429653766#/subjects/ASW00020xy

@drphilmarshall - I could check with some guidance but i don't seem to be able to download the images 

Do you remember if Anu had a tolerance parameter in the distance between the x,y makr and the mask - perhaps this may be set to the VICS82 rather than CFHTLS value? If I recall correctly i think this was build into the mask rather than into checking the marker position.

**Comment by chrissnyder** [comment]
Will be looking at this over the weekend.

**Comment by drphilmarshall** [comment]
Thanks @chrissnyder, you're a star. I meant to mention this from #286 just now - there are some hints there I think.

**Comment by aprajita** [comment]
Thanks @chrissnyder, as this seems to be affecting a lot of people, we really need to fix this asap before people are turned off from the site/project. 

@drphilmarshall do you have any ideas where this comes from so that it's easier to diagnose?

**Comment by drphilmarshall** [comment]
I put some links to other issues - I suspect it's to do with vics82
settings being used for CFHTLS images. The image sizes were different, so
the coordinate system that the markers are using could be wrong.

**Comment by aprajita** [comment]
Hi @chrissnyder 
I hope you don't mind, but I was looking at 
https://github.com/zooniverse/Lens-Zoo/blob/a8ca72585a958a1824d8278f0865579b36655b0f/app/controllers/classifier.coffee#L364
which has a 10 pixel hack for the annotation position (due to a missing line in the interface I think) and was wondering if this is part of this sim message issue? 

As well as determining the location of the success message, y is also being used to test for the feedback message (see line 432), and thus it might be 10 pixels off from the mask in y - 

As there's a tolerance in anu's mask, it could be that some inaccurate hits still stay inside the good regions of the mask but sometimes they are out - this may explain the mixture of success and non-success images

Do you think this might be the cause of the mismatched marker & sim feedback messages...?

I see the same thing is done in the VICS82 branch so am not sure why we didnt have such problems then (if this is the cause).

**Comment by chrissnyder** [comment]
Maybe, but there also should be plenty of margin of error in the detection, so 10px in any direction shouldn't matter.

I made some changes in e27f571287fa25dee1e05c8e98614596e4c0d493 which fixes this problem under certain conditions. Not sure if I got everything.

**Comment by drphilmarshall** [comment]
Great, thanks @chrissnyder! I see correct messages now, at least in the
short test run I just did. I posted to the discussion at
http://talk.spacewarps.org/?_ga=1.203581264.1585278771.1428907215#/boards/BSW0000007/discussions/DSW0000epy
- could be good to monitor this to see if everyone else's problems are
solved too.

Thanks again!

**Comment by aprajita** [comment]
i did a check of >200 images and only got errors on those i missed - thanks for fixing this @chrissnyder!

**Comment by aprajita** [comment]
closing this as I think it's solved (finger's crossed)...
